#include <catch2/catch_test_macros.hpp>
#include <filesystem>
#include <fstream>
#include <set>
#include <string>
#include "daemon/repo.hpp"
#include "tests/test_paths.hpp"

TEST_CASE("every url form of one repo collapses to one key") {
    std::set<std::string> keys{
        ap::normalize_remote("git@github.com:acme/api.git"),
        ap::normalize_remote("https://github.com/acme/api"),
        ap::normalize_remote("https://github.com/acme/api.git"),
        ap::normalize_remote("ssh://git@github.com/acme/api.git"),
        ap::normalize_remote("HTTPS://GitHub.com/Acme/API.git"),
        ap::normalize_remote("https://github.com/acme/api/"),
    };
    REQUIRE(keys.size() == 1);
    REQUIRE(*keys.begin() == "github.com/acme/api");
}

namespace {

struct Vector {
    const char* url;
    const char* normalized;
    const char* room_id;
};

// Generated by running the Python implementation, not by running this one:
//
//   cd python && ./.venv/bin/python -c '
//   from agent_presence.room_key import normalize_remote, room_id_from_remote
//   for c in cases: print(room_id_from_remote(c), repr(normalize_remote(c)))'
//
// Non-ASCII is deliberately left unfolded: normalization is ASCII-only by
// contract on both sides, because C++ has no Unicode case mapping in the
// standard library and a room key that disagrees across languages splits a team
// into two rooms. See the note in room_key.py.
const Vector kPythonVectors[] = {
    // ssh/scp, https, .git, case, trailing slash — all one repo.
    {"git@github.com:acme/api.git", "github.com/acme/api", "e1dcaa3496b93562"},
    {"https://github.com/acme/api", "github.com/acme/api", "e1dcaa3496b93562"},
    {"https://github.com/acme/api.git", "github.com/acme/api", "e1dcaa3496b93562"},
    {"ssh://git@github.com/acme/api.git", "github.com/acme/api", "e1dcaa3496b93562"},
    {"HTTPS://GitHub.com/Acme/API.git", "github.com/acme/api", "e1dcaa3496b93562"},
    {"https://github.com/acme/api/", "github.com/acme/api", "e1dcaa3496b93562"},
    // Whitespace git config picks up. \x1d is whitespace to str.strip() too.
    {"  https://github.com/acme/api.git \n", "github.com/acme/api", "e1dcaa3496b93562"},
    {"https://github.com/acme/api.git\x1d", "github.com/acme/api", "e1dcaa3496b93562"},
    // Non-ASCII: case is left alone, and U+00A0 is not whitespace here.
    {"https://github.com/acme/\xc3\x9c" "nicode-Repo.git",
     "github.com/acme/\xc3\x9c" "nicode-repo", "2707d06139ada0c0"},
    {"git@gitlab.com:\xc3\x89" "QUIPE/Projet.git",
     "gitlab.com/\xc3\x89" "quipe/projet", "fbcc8d6b93e2a37f"},
    {"\xc2\xa0" "https://github.com/acme/api.git\xc2\xa0",
     "\xc2\xa0" "https://github.com/acme/api.git\xc2\xa0", "a2204ca2a2dbc8dc"},
    // A bare CR mid-remote: python's `.` does not match \n but does match \r.
    {"git@host:pa\rth", "host/pa\rth", "cab7f1fc89970e3a"},
    // Different repos, different rooms.
    {"git@github.com:acme/web.git", "github.com/acme/web", "6622211c92d781b7"},
    {"git@gitlab.com:acme/api.git", "gitlab.com/acme/api", "1055cc0317804d28"},
};

}  // namespace

TEST_CASE("room id matches the python implementation byte for byte") {
    for (const auto& v : kPythonVectors) {
        INFO("url: " << v.url);
        CHECK(ap::normalize_remote(v.url) == std::string(v.normalized));
        CHECK(ap::room_id_from_remote(v.url) == std::string(v.room_id));
    }
}

TEST_CASE("distinct repos and hosts stay distinct") {
    REQUIRE(ap::normalize_remote("git@github.com:acme/api.git")
            != ap::normalize_remote("git@github.com:acme/web.git"));
    REQUIRE(ap::normalize_remote("git@github.com:acme/api.git")
            != ap::normalize_remote("git@gitlab.com:acme/api.git"));
}

TEST_CASE("find_repo_root walks up to the marker and gives up at the top") {
    namespace fs = std::filesystem;
    const auto base = fs::path(apt::unique_temp_path("ap_repo_test"));
    fs::remove_all(base);
    const auto deep = base / "repo" / "src" / "nested";
    fs::create_directories(deep);
    // A worktree's .git is a file, so test the file form.
    { std::ofstream marker(base / "repo" / ".git"); marker << "gitdir: elsewhere\n"; }

    auto found = ap::find_repo_root(deep.string());
    REQUIRE(found.has_value());
    REQUIRE(fs::equivalent(*found, base / "repo"));

    // No marker anywhere above the filesystem root.
    REQUIRE_FALSE(ap::find_repo_root("/").has_value());

    fs::remove_all(base);
}
